### ISSUE TITLE
add Plausible tracking

### ISSUE THREAD

**Issue by marcoow** [mainmatter/sheepdog#214]
We need to add the Plausible tracking snippet to the `<head>` of the landing page:

```html
<script defer data-domain="sheepdog.run" src="https://plausible.io/js/script.js"></script>
```

I don't know how to do that in Astro…

**Comment by paoloricciuti** [comment]
> We need to add the Plausible tracking snippet to the `<head>` of the landing page:
> 
> ```
> <script defer data-domain="sheepdog.run" src="https://plausible.io/js/script.js"></script>
> ```
> 
> I don't know how to do that in Astro…

Shouldn't we also add some kind of client Id for main matter?

**Comment by marcoow** [comment]
no, that's all
